# **Financial Market News Sentiment Analysis**

## **Objective**

The objective of this project is to perform sentiment analysis on top 25 financial news(fictional data) using suitable classification algorithms.

### Data Source: 
The data is available on the Git Hub repository of YBI Foundation.
Link: https://github.com/YBI-Foundation/Dataset/blob/main/Financial%20Market%20News.csv

### Import Library

In [1]:
import pandas as pd

In [2]:
import numpy as np

### Import Data

In [3]:
df = pd.read_csv(r'/kaggle/input/financial-market-dataset-fictional/YBI-Foundation_Dataset_main_Financial_Market_News.csv', encoding = "ISO-8859-1")

### Describe Data

In [4]:
df.head()

Date  Label                                             News 1  \
0  01-01-2010      0           McIlroy's men catch cold from Gudjonsson   
1  02-01-2010      0               Warning from history points to crash   
2  03-01-2010      0      Comment: Why Israel's peaceniks feel betrayed   
3  04-01-2010      1             £750,000-a-goal Weah aims parting shot   
4  05-01-2010      1  Leeds arrive in Turkey to the silence of the fans   

                                       News 2  \
0                       Obituary: Brian Walsh   
1              Investors flee to dollar haven   
2  Court deals blow to seizure of drug assets   
3            Newcastle pay for Fletcher years   
4     One woman's vision offers loan lifeline   

                                            News 3  \
0       Workplace blues leave employers in the red   
1                      Banks and tobacco in favour   
2                       An ideal target for spooks   
3  Brown sent to the stands for Scotland qualifier   
4          Working Lives: How world leaders worked   

                                        News 4  \
0                     Classical review: Rattle   
1                        Review: Llama Farmers   
2  World steps between two sides intent on war   
3         Tourists wary of breaking new ground   
4           Working Lives: Tricks of the trade   

                                              News 5  \
0                     Dance review: Merce Cunningham   
1                       War jitters lead to sell-off   
2                       What the region's papers say   
3              Canary Wharf climbs into the FTSE 100   
4  Working Lives: six-hour days, long lunches and...   

                                         News 6  \
0  Genetic tests to be used in setting premiums   
1                    Your not-so-secret history   
2           Comment: Fear and rage in Palestine   
3                           Review: Bill Bailey   
4                        Pop review: We Love UK   

                                          News 7  \
0                        Opera review: La Bohème   
1                  Review: The Northern Sinfonia   
2  Poverty and resentment fuels Palestinian fury   
3                              Review: Classical   
4               World music review: Marisa Monte   

                                        News 8  ...  \
0                   Pop review: Britney Spears  ...   
1                             Review: Hysteria  ...   
2  Republican feud fear as dissident is killed  ...   
3              Review: New Contemporaries 2000  ...   
4             Art review:  Hollingsworth/Heyer  ...   

                                News 16                              News 17  \
0                 Finland 0 - 0 England                   Healy a marked man   
1  Why Wenger will stick to his Gunners  Out of luck England hit rock bottom   
2             FTSE goes upwardly mobile             At this price?  BP Amoco   
3         More cash on way for counties      Cairns carries Kiwis to victory   
4          Duisenberg in double trouble           Pru to cut pension charges   

                                             News 18  \
0                     Happy birthday Harpers & Queen   
1                         Wilkinson out of his depth   
2                                            Go fish   
3  Year of Blanchflower's flourish when Spurs sto...   
4                            Art review: Paul Graham   

                                             News 19  \
0  Win unlimited access to the Raindance film fes...   
1                   Kinsella sparks Irish power play   
2         Bosnian Serb blows himself up to evade law   
3      New direct approach brings only pay-per-blues   
4               Shearer shot sparks Boro humiliation   

                                             News 20  \
0  Labour pledges £800m to bridge north-south divide   
1                    Brown banished as Scots rebound   
2                       Or

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4101 entries, 0 to 4100
Data columns (total 27 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Date     4101 non-null   object
 1   Label    4101 non-null   int64 
 2   News 1   4101 non-null   object
 3   News 2   4101 non-null   object
 4   News 3   4101 non-null   object
 5   News 4   4101 non-null   object
 6   News 5   4101 non-null   object
 7   News 6   4101 non-null   object
 8   News 7   4101 non-null   object
 9   News 8   4101 non-null   object
 10  News 9   4101 non-null   object
 11  News 10  4101 non-null   object
 12  News 11  4101 non-null   object
 13  News 12  4101 non-null   object
 14  News 13  4101 non-null   object
 15  News 14  4101 non-null   object
 16  News 15  4101 non-null   object
 17  News 16  4101 non-null   object
 18  News 17  4101 non-null   object
 19  News 18  4101 non-null   object
 20  News 19  4101 non-null   object
 21  News 20  4101 non-null   object
 22  

In [6]:
df.shape

(4101, 27)

In [7]:
df.columns

Index(['Date', 'Label', 'News 1', 'News 2', 'News 3', 'News 4', 'News 5',
       'News 6', 'News 7', 'News 8', 'News 9', 'News 10', 'News 11', 'News 12',
       'News 13', 'News 14', 'News 15', 'News 16', 'News 17', 'News 18',
       'News 19', 'News 20', 'News 21', 'News 22', 'News 23', 'News 24',
       'News 25'],
      dtype='object')

### Data Preprocessing

In [8]:
' '.join(str(x) for x in df.iloc[1,2:27])

"Warning from history points to crash Investors flee to dollar haven Banks and tobacco in favour Review: Llama Farmers War jitters lead to sell-off Your not-so-secret history Review: The Northern Sinfonia Review: Hysteria Review: The Guardsman Opera: The Marriage of Figaro Review: The Turk in Italy Deutsche spells out its plans for diversification Traders' panic sends oil prices skyward TV sport chief leaves home over romance Leader: Hi-tech twitch Why Wenger will stick to his Gunners Out of luck England hit rock bottom Wilkinson out of his depth Kinsella sparks Irish power play Brown banished as Scots rebound Battling Wales cling to lifeline Ehiogu close to sealing Boro move Man-to-man marking Match stats French referee at centre of storm is no stranger to controversy"

In [9]:
df.index

RangeIndex(start=0, stop=4101, step=1)

In [10]:
len(df.index)

4101

In [11]:
news = []

In [12]:
for row in range(0, len(df.index)):
  news.append(' '.join(str(x) for x in df.iloc[row, 2:27]))

In [13]:
type(news)

list

In [14]:
news[0]

"McIlroy's men catch cold from Gudjonsson Obituary: Brian Walsh Workplace blues leave employers in the red Classical review: Rattle Dance review: Merce Cunningham Genetic tests to be used in setting premiums Opera review: La Bohème Pop review: Britney Spears Theatre review: The Circle Wales face a fraught night Under-21  round-up Smith off to blot his copybook Finns taking the mickey Praise wasted as Brown studies injury options Ireland wary of minnows Finland 0 - 0 England Healy a marked man Happy birthday Harpers & Queen Win unlimited access to the Raindance film festival Labour pledges £800m to bridge north-south divide Wales: Lib-Lab pact firm despite resignation Donald Dewar Regenerating homes  regenerates well-being in people Win £100 worth of underwear TV guide: Random views"

In [15]:
X = news

In [16]:
type(X)

list

### Define Target Variable (y) and Feature Variables (X)

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
cv = CountVectorizer(lowercase=True, ngram_range = (1,1))

In [19]:
X = cv.fit_transform(X)

In [20]:
X.shape

(4101, 48527)

In [21]:
y = df['Label']

In [22]:
y.shape

(4101,)

### Train Test Split

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=2529)

# Random Forest Classifier

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
rf = RandomForestClassifier(n_estimators=200)

In [27]:
rf.fit(x_train, y_train)

RandomForestClassifier(n_estimators=200)

In [28]:
y_pred = rf.predict(x_test)

In [29]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

## Random Forest Model Accuracy

In [30]:
confusion_matrix(y_test,y_pred)

array([[148, 433],
       [157, 493]])

In [31]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.49      0.25      0.33       581
           1       0.53      0.76      0.63       650

    accuracy                           0.52      1231
   macro avg       0.51      0.51      0.48      1231
weighted avg       0.51      0.52      0.49      1231



In [32]:
accuracy_score(y_test,y_pred)

0.5207148659626321

# SVM Classifier

In [33]:
from sklearn.svm import SVC

svm = SVC()

In [34]:
svm.fit(x_train, y_train)

SVC()

In [35]:
y_pred = svm.predict(x_test)

## SVM Model Accuracy

In [36]:
confusion_matrix(y_test, y_pred)

array([[ 83, 498],
       [107, 543]])

In [37]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.44      0.14      0.22       581
           1       0.52      0.84      0.64       650

    accuracy                           0.51      1231
   macro avg       0.48      0.49      0.43      1231
weighted avg       0.48      0.51      0.44      1231



In [38]:
accuracy_score(y_test, y_pred)

0.5085296506904955

# Logistic Regression

In [39]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(max_iter=1000)

In [40]:
logreg.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [41]:
y_pred = logreg.predict(x_test)

## Logistic Regression Accuracy

In [42]:
confusion_matrix(y_test,y_pred)

array([[266, 315],
       [325, 325]])

In [43]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.45      0.46      0.45       581
           1       0.51      0.50      0.50       650

    accuracy                           0.48      1231
   macro avg       0.48      0.48      0.48      1231
weighted avg       0.48      0.48      0.48      1231



In [44]:
accuracy_score(y_test, y_pred)

0.4800974817221771

# Explanation

In this project we have performed sentiment analysis on the top 25 financial dataset using Random Forest Classifier, SVM(Support Vector Machine) and Logistic Regression. Then they are compared based on the performance measures. By analysing the various outcomes of the three models we can see that SVM and Random Forest performed best for the analysis. All the required preprocessing of data and feature engineering were performed on the dataset available.